### ISSUE TITLE
Research mongo indexes with keys > 1K

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#26]
Mongo server 3.x had a limitation that indexed keys could not be over 1K of data.  This led to the pattern where we use `database.hash()` on all indexed fields.

Mongo 4.x has removed this limitation.

It was thought that we would have to upgrade to Mongo JS Driver 3.x in order to use Mongo Server 4.  Today, we know that is not the case.  We are able to successfully using the 2.x driver we're using now with Mongo4 and no issues have been identified with this configuration in the months we've been using it.

The question is, can we use indexed fields greater than 1K when using Mongo 4 server today, without having to upgrade the node driver to 3.x?

**Comment by mattcollier** [comment]
Mongo Server 3.x and 4.x produce the same error from the mongo-core driver currently used in bedrock-mongodb.
```
MongoError: WiredTigerIndex::insert: key too large to index, failing  3012 { : "486038657097590591094921571768013919539636479074471573249380079538392369870834888895514000535894759912368850322158837914721938820280203386443112662293..." }
    at Function.MongoError.create (/home/matt/dev/test-mongo-index/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/matt/dev/test-mongo-index/node_modules/mongodb/lib/utils.js:139:22)
    at /home/matt/dev/test-mongo-index/node_modules/mongodb/lib/collection.js:668:23
    at handleCallback (/home/matt/dev/test-mongo-index/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/home/matt/dev/test-mongo-index/node_modules/mongodb/lib/bulk/ordered.js:421:14)
    at /home/matt/dev/test-mongo-index/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Test harness here: https://github.com/mattcollier/test-mongo-index/blob/master/index.js#L36-L58

**Comment by davidlehn** [comment]
MongoDB is removing the "Index Key Limit" in 4.2: https://docs.mongodb.com/master/reference/limits/#Index-Key-Limit

**Comment by mattcollier** [comment]
Installed mongo 4.2 RC3, it *does* require the 3.0 driver.
```
2019-07-18T21:29:19.307Z - critical: worker: uncaught error: error=DatabaseError: Could not initialize database.
    at async.auto.err (/home/ubuntu/test-mongo-index/node_modules/bedrock-mongodb/lib/index.js:180:23)
    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:473:16
    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1622:17
    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:969:16
    at process.runOnce (/home/ubuntu/test-mongo-index/node_modules/bedrock/lib/bedrock.js:232:14)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19), workerPid=29112, details={
  "name": "DatabaseError",
  "message": "Could not initialize database.",
  "details": {
    "url": "mongodb://localhost:27017/bedrock_dev"
  },
  "cause": {
    "name": "DatabaseError",
    "message": "Could not initialize database.",
    "stack": "DatabaseError: Could not initialize database.\n    at _openDatabase (/home/ubuntu/test-mongo-index/node_modules/bedrock-mongodb/lib/index.js:577:25)\n    at async.auto.err (/home/ubuntu/test-mongo-index/node_modules/bedrock-mongodb/lib/index.js:707:13)\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:473:16\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1622:17\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:969:16\n    at async.auto.serverCheck (/home/ubuntu/test-mongo-index/node_modules/bedrock-mongodb/lib/index.js:656:18)\n    at runTask (/home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1632:13)\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1572:13\n    at processQueue (/home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1582:13)\n    at taskComplete (/home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1601:9)",
    "details": {
      "url": "mongodb://localhost:27017/bedrock_dev"
    },
    "cause": {
      "name": "DatabaseError",
      "message": "Unsupported database version.",
      "stack": "DatabaseError: Unsupported database version.\n    at async.auto.serverCheck (/home/ubuntu/test-mongo-index/node_modules/bedrock-mongodb/lib/index.js:656:27)\n    at runTask (/home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1632:13)\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1572:13\n    at processQueue (/home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1582:13)\n    at taskComplete (/home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1601:9)\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:1625:17\n    at /home/ubuntu/test-mongo-index/node_modules/async/dist/async.js:969:16\n    at /home/ubuntu/test-mongo-index/node_modules/mongodb/lib/admin.js:126:5\n    at handleCallback (/home/ubuntu/test-mongo-index/node_modules/mongodb/lib/utils.js:120:56)\n    at /home/ubuntu/test-mongo-index/node_modules/mongodb/lib/db.js:998:7",
      "details": {
        "url": "mongodb://localhost:27017/bedrock_dev",
        "version": "4.2.0-rc3",
        "required": ">=3.0"
      },
      "cause": null
    }
  }
}

```

**Comment by mattcollier** [comment]
This implementation using the 3.x driver fails as expected with mongo 3.x server, but succeeds on mongo 4.2RC3.  No special configuration required.

https://github.com/mattcollier/test-mongo-index/tree/driver-3

**Comment by mattcollier** [comment]
Added an explain which confirms that query on ID is a covered query and that index was used as expected, showing one key examined and zero documents examined:

https://gist.github.com/mattcollier/a6000fc9f34a02245b921c9fd3736db9#file-some-json-L14

**Comment by dlongley** [comment]
We have upgraded to the 3.x driver, so this has become irrelevant, closing.
