### ISSUE TITLE
UnhandledPromiseRejectionWarning if mongodb is not running or reachable.

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-mongodb#31]
I'm not sure if this is an issue with Bedrock.runOnce/runOnceAsync or the way it's implemented here.  

The cause of this error is that the mongodb server is not running or reachable.

The issue is that we have an `UnhandledPromiseRejectionWarning` that I believe *should* cause Bedrock to exit with an error condition.  Instead, bootstrapping proceeds and things go downhill fast.

In CI, this leads to hangs/timeouts when apparently the database initialization stuffs retry indefinitely.

```
Run cd test

> bedrock-profile-http-test@0.0.1-0 coverage-ci /home/runner/work/bedrock-profile-http/bedrock-profile-http/test
> cross-env NODE_ENV=test nyc --reporter=text-lcov npm test > coverage.lcov

(node:2853) DeprecationWarning: runOnceAsync() is deprecated. Use runOnce() instead.
(node:2853) UnhandledPromiseRejectionWarning: DatabaseError: Could not initialize database.
    at /home/runner/work/bedrock-profile-http/bedrock-profile-http/test/node_modules/bedrock-mongodb/lib/index.js:180:23
    at /home/runner/work/bedrock-profile-http/bedrock-profile-http/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:473:16
    at /home/runner/work/bedrock-profile-http/bedrock-profile-http/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:1622:17
    at /home/runner/work/bedrock-profile-http/bedrock-profile-http/test/node_modules/bedrock-mongodb/node_modules/async/dist/async.js:969:16
    at cb (util.js:207:31)
    at util.js:191:10
    at hidden (internal/errors.js:289:14)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dlongley** [comment]
This should be fixed with the latest version of bedrock, closing.
